Draft-023
authwit/content-briefsweekly pull request #16
Opened 2021-06-29 14:13 UTC by ESTHER0533

@deletosh Add draft 023

2021-07-05 21:59 UTC, deletosh requested changes
@ESTHER0533 please see notes in the review and update

2021-07-05 21:59 UTC, deletosh commented on draft-023.md
> +Businesses around the world continue to feel the pandemic’s impact in countless ways. Most in-house legal departments still grapple with the challenges of working remotely, making do with leaner budg
@ESTHER0533 let's end this (and all the other sections) with an entising lead that encourages them to click into the article.

2021-07-05 21:59 UTC, deletosh commented on draft-023.md
> +[Will artificial intelligence replace lawyers? - MikeLegal](https://blog.mikelegal.com/legaltech/will-artificial-intelligence-replace-lawyers/)
@ESTHER0533 exclude the name of the source in the tilte, e.g. in this "MikeLegal" and same for the others

2021-07-06 11:29 UTC, ESTHER0533 commented on draft-023.md
> +[Will artificial intelligence replace lawyers? - MikeLegal](https://blog.mikelegal.com/legaltech/will-artificial-intelligence-replace-lawyers/)
@deletosh please throw more light on this, i dont understand this part

2021-07-06 11:30 UTC, ESTHER0533 commented on draft-023.md
> +Businesses around the world continue to feel the pandemic’s impact in countless ways. Most in-house legal departments still grapple with the challenges of working remotely, making do with leaner budg
@deletosh do you mean, (and all the other sections) should come after opportunity??

2021-07-20 22:55 UTC, deletosh commented on draft-023.md
> +[Will artificial intelligence replace lawyers? - MikeLegal](https://blog.mikelegal.com/legaltech/will-artificial-intelligence-replace-lawyers/)
@ESTHER0533  don't inlude "MikeLegal"

2021-07-20 22:58 UTC, merged